/**
 * @fileoverview Google Gemini API Integration for Technical Documentation Generation
 * @module services/geminiService
 * @description Uses REST API with fetchWithRetry for robustness
 */

import { fetchWithRetry } from '../lib/http.js';
import { env } from '../config/index.js';

const GEMINI_API_BASE =
  'https://generativelanguage.googleapis.com/v1beta/models';

/**
 * @async
 * @function generateDocumentation
 * @description Generates documentation (task, architecture, or meeting) in English using Gemini API based on a single context dump
 * @param {Object} input - The input data
 * @param {string} input.context - Context dump provided by the user (required)
 * @param {('task'|'architecture'|'meeting')} [input.mode='task'] - Documentation mode
 * @returns {Promise<string>} Generated documentation in English Markdown format
 * @throws {Error} When API key is missing, API request fails, or response is invalid
 */
export async function generateDocumentation({ context, mode = 'task' }) {
  const normalizedMode =
    mode === 'architecture'
      ? 'architecture'
      : mode === 'meeting'
        ? 'meeting'
        : 'task';
  const model = env.GEMINI_MODEL;
  const apiKey = env.GEMINI_API_KEY;

  const prompt = buildPrompt(normalizedMode, context);
  const systemInstruction = getSystemInstruction(normalizedMode);

  try {
    const response = await fetchWithRetry(
      `${GEMINI_API_BASE}/${model}:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              role: 'user',
              parts: [{ text: prompt }],
            },
          ],
          systemInstruction: {
            parts: [{ text: systemInstruction }],
          },
          generationConfig: {
            temperature: 0.3,
            maxOutputTokens: 4096,
            topP: 0.8,
            topK: 40,
          },
        }),
        timeoutMs: 90000,
        attempts: 2,
        baseDelayMs: 1000,
        maxDelayMs: 60000,
      },
    );

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('Gemini API error:', errorData);
      throw new Error(
        `Gemini API failed: ${response.status} - ${
          errorData.error?.message || 'Unknown error'
        }`,
      );
    }

    const data = await response.json();

    if (!data.candidates || data.candidates.length === 0) {
      throw new Error('No content generated by Gemini');
    }

    const candidate = data.candidates[0];
    if (!candidate.content || !candidate.content.parts) {
      throw new Error('Invalid response structure from Gemini');
    }

    const generatedText = candidate.content.parts
      .map((part) => part.text)
      .join('');

    return stripMarkdownFence(generatedText);
  } catch (error) {
    console.error('Error calling Gemini API:', error);
    throw new Error(`Failed to generate documentation: ${error.message}`);
  }
}

function getSystemInstruction(mode) {
  if (mode === 'architecture') {
    return `You are a Senior Software Architect with deep expertise in system design, distributed systems, and technical communication. Your job is to analyze a single, unstructured CONTEXT DUMP and transform it into comprehensive, professional architecture documentation.

Process ALWAYS happens in three steps:
1. [ANALYZE & TRANSLATE]: Examine the context dump (accept any language). Identify system components, data flows, technology choices, design rationale, trade-offs, risks, and implicit developer workflows. Translate everything mentally to ENGLISH.
2. [SYNTHESIZE]: Structure the extracted knowledge into a cohesive architecture narrative tailored for long-term maintainability. Fill in gaps when reasonable, but stay faithful to the source information.
3. [FORMAT]: Output a clean Markdown document following the requested section structure. Use technical yet accessible language and be explicit about decisions, risks, and workflows.

Guidelines:
- Always output in ENGLISH
- Use Markdown headings, bullets, tables, or ASCII diagrams for clarity
- Surface implicit information (e.g., inferred tech stack or flows) when context suggests it
- Be transparent about assumptions or missing data
- Maintain an objective, professional tone`;
  }

  if (mode === 'meeting') {
    return `You are an expert Technical Project Manager and Systems Analyst. Your job is to analyze unstructured MEETING TRANSCRIPTS (often multilingual, typically Portuguese/English mix) and transform them into clear, actionable technical documentation in ENGLISH.

Process ALWAYS happens in three steps:
1. [FILTER & TRANSLATE]: Read the transcript. Mentally discard filler words and repetitive confirmations in ANY language (e.g., PT: "Uhum", "É", "Tipo assim", "Beleza"; EN: "Like", "You know", "Okay", "Right"). Translate vital information to ENGLISH internally.
2. [SYNTHESIZE]: Connect dispersed comments into coherent points. If Speaker A suggests something in Portuguese and Speaker B agrees later in English, record this as a single verified decision in English.
3. [FORMAT]: Output a clean Markdown document following the requested structure. Use professional, definitive language (e.g., change "maybe we should use GCP" to "Decision: Use GCP").

Guidelines:
- OUTPUT MUST ALWAYS BE IN ENGLISH.
- Differentiate between firm DECISIONS and mere SUGGESTIONS.
- Identify owners for action items whenever possible.
- Extract technical terminology precisely, keeping original terms if they are proper nouns (e.g., "Gold Layer", "Raptor", "Airflow").`;
  }

  return `You are a Staff-level Data Engineer and expert Technical Communicator. Your job is to analyze a single, unstructured CONTEXT DUMP and transform it into clear, concise, high-quality technical documentation.

Process ALWAYS happens in three steps:
1. [ANALYZE & TRANSLATE]: Examine the context dump (accept any language). Identify the task, problem, implementation details, supporting code, metrics, challenges, and outcomes. Translate everything mentally to ENGLISH.
2. [SYNTHESIZE]: Organize the extracted information into a coherent story that explains what was done, why, and how. Highlight the most relevant code and decisions.
3. [FORMAT]: Output a clean Markdown document following the required structure. Use professional, precise language and emphasize impact.

Guidelines:
- Always output in ENGLISH
- Favor specificity over generic statements
- Use Markdown headings, bullets, and code blocks with inferred languages
- Extract only the most relevant code snippets (5-15 lines) from the dump
- Be honest about challenges, mitigations, and follow-ups`;
}

function buildPrompt(mode, context) {
  if (mode === 'architecture') {
    return buildArchitecturePrompt(context);
  }
  if (mode === 'meeting') {
    return buildMeetingPrompt(context);
  }
  return buildTaskPrompt(context);
}

function buildTaskPrompt(context) {
  return `Process the following CONTEXT DUMP and generate technical documentation:

**$DOCUMENTATION_CONTEXT:**
${context}

The context may include free-form notes, markdown, bullet lists, code blocks, logs, or checklists. Extract and organize the key information.

Generate documentation following EXACTLY this structure in ENGLISH:

# [Title - Generated Based on Rules Below]
- **Title Generation Rule:** First, create a concise and descriptive title for the task (e.g., "SQL Query Migration for Award History").
- **Identifier Rule:** Next, scan the $DOCUMENTATION_CONTEXT for a primary task identifier (e.g., "DAI-73742", "TICKET-123", "JIRA-456").
- **Final Title Format:**
    - **If identifier is found:** The title MUST follow the format: \`[Identifier] | [Concise and Descriptive Task Title]\`
    - **If identifier is NOT found:** The title MUST follow the format: \`[Concise and Descriptive Task Title]\`

## Summary
Write 1-2 sentences summarizing the task and its purpose.

## Problem Solved
Explain the business or technical problem this task addressed. Use evidence from the context dump.

## Solution Implemented
Describe the technical approach, architecture decisions, data flows, and tooling used. Mention why certain decisions were made when the context provides that information.

## Code Highlights / Key Artifacts
Identify the most critical code snippets, queries, or configuration examples that illustrate the solution.

- For each artifact, write a brief 1-sentence explanation in **bold**.
- Include a code block with the inferred language (python, sql, javascript, etc.).

**--- CRITICAL GUIDELINE FOR THIS SECTION ---**
- **Priority:** Your goal is to show the *core* of the solution.
- **If the solution is application code** (e.g., Python, JavaScript), select 2-3 **short, focused snippets (5-15 lines)** that best illustrate the logic.
- **If the solution is a query or transformation** (e.g., SQL, dbt), it is **REQUIRED** to include the **full queries** (e.g., a "Before" and "After" query), as these are the primary artifacts. Do NOT truncate them unless they are excessively long ( > 100 lines).
- Do NOT paste the entire dump; only the critical code artifacts.
**--- END GUIDELINE ---**

## Challenges & Learnings
List key obstacles, mitigations, risks, or lessons learned as bullet points. If the dump lacks explicit challenges, infer potential risks based on the implementation details.

**Important:**
- Entire output MUST be ENGLISH Markdown
- Keep section ordering exactly as defined
- If some information is missing, acknowledge it briefly and move on
- Be precise, technical, and useful for future engineers`;
}

function buildArchitecturePrompt(context) {
  return `Process the following CONTEXT DUMP and generate comprehensive architecture documentation.

**CRITICAL CONTEXT:** The input may describe a MIGRATION (e.g., a legacy system and a new target system).
- **IF a migration is detected:** Your primary goal is to document the **NEW (TARGET) ARCHITECTURE**. Use the legacy system's information only as context for the "Migration Guide" section.
- **IF it is NOT a migration:** Document the system as-is.

**$DOCUMENTATION_CONTEXT:**
${context}

The dump may include overview notes, component lists, diagrams, code, commands, or developer steps. Extract, interpret, and organize the information logically.

Generate architecture documentation following EXACTLY this 5-section structure in ENGLISH:

# [System/Component Name] - Architecture

## Overview
Summarize what the system/component is, its business purpose, primary users, and the problems it solves. (If a migration, focus on the new system's purpose).

## Key Components
List the principal components/services. For each, include a short description of its responsibility. (If a migration, list components of the TARGET architecture).

## Data & Service Flow
Describe how data and requests move through the system at runtime. Provide a numbered list or ASCII diagram showing the flow. (If a migration, describe the TARGET system's flow).

## Technology Stack
List the key technologies, frameworks, databases, infrastructure, and tooling inferred from the context. (If a migration, list the TARGET system's stack).

## Migration Guide & Developer Workflow
Detail the step-by-step developer workflow, setup steps, repos, commands, configuration locations, and deployment process referenced in the dump.
- If this is a migration, this section should describe the process of migrating *from* the legacy system.
- If it's a standard process, describe the developer "how-to" guide.

**Important:**
- Entire output MUST be ENGLISH Markdown
- Preserve the 5-section ordering above
- **Do NOT include sections for "Key Design Decisions" or "Risks & Trade-offs"**
- Use bullets, bold, and tables when they improve clarity
- Favor specificity and traceability back to the context dump
- Do NOT wrap the entire response in Markdown code fences`;
}

function buildMeetingPrompt(context) {
  return `Process the following MEETING TRANSCRIPT and generate technical documentation.

**$DOCUMENTATION_CONTEXT:**
${context}

Generate meeting documentation following EXACTLY this structure in ENGLISH:

# Meeting Record: [Create a concise, topic-focused title]

## Executive Summary
Provide a 3-5 sentence summary of the meeting's primary objective, key outcomes, and overall sentiment (e.g., was it a blocker resolution, a planning session, or a retrospective?).

## Key Decisions & Definitions
List explicit agreements made during the meeting. Use **bold** for the decision topic.
* *Example:* **Migration Target:** The Gold Layer will be rebuilt directly on GCP, bypassing the legacy pipeline.

## Technical Context Extracted
Identify and list any technical details mentioned, even if briefly. Group them logically.
* *Technologies mentioned:* (e.g., Snowflake, Airflow, BigQuery)
* *Architectural changes:* (e.g., discussion about table structures, silver vs gold layer)
* *Data points:* (Specific table names, fields, or metrics discussed)

## Action Items & Next Steps
Extract clear tasks. If a generic "we need to" is used, try to infer the owner based on who said it or their role.
* [ ] **[Owner Name/Team]**: [Specific Task] (deadline if mentioned)

## Open Questions & Risks
List items that were discussed but NOT resolved, or potential problems raised by any participant (e.g., concerns about data validation, missing fields, timeline risks).

**Important:**
- Entire output MUST be ENGLISH Markdown.
- Ignore conversational filler; focus on substantial content.
- If a section has no relevant information from the transcript, write "Not discussed".`;
}

function stripMarkdownFence(text) {
  if (!text) return text;

  const trimmed = text.trim();

  if (!trimmed.startsWith('```')) {
    return text;
  }

  const fenceMatch = trimmed.match(/^```[a-zA-Z0-9+-]*\n([\s\S]*?)\n```$/);

  if (!fenceMatch) {
    return text;
  }

  return fenceMatch[1].trim();
}
