/**
 * @fileoverview Groq API Integration for Technical Documentation Generation
 * @module services/groqService
 * @description Uses Groq's ultra-fast LLM API with Llama models
 */

import { fetchWithRetry } from '../lib/http.js';
import { env } from '../config/index.js';

const GROQ_API_BASE = 'https://api.groq.com/openai/v1';

/**
 * @async
 * @function generateDocumentation
 * @description Generates documentation using Groq API (Llama 3.3 70B)
 * @param {Object} input - The input data
 * @param {string} input.context - Context dump provided by the user
 * @param {('task'|'architecture'|'meeting')} [input.mode='task'] - Documentation mode
 * @returns {Promise<string>} Generated documentation in English Markdown format
 * @throws {Error} When API key is missing, API request fails, or response is invalid
 */
export async function generateDocumentation({ context, mode = 'task' }) {
  const normalizedMode =
    mode === 'architecture'
      ? 'architecture'
      : mode === 'meeting'
        ? 'meeting'
        : 'task';

  const apiKey = env.GROQ_API_KEY;
  const model = env.GROQ_MODEL || 'llama-3.3-70b-versatile';

  if (!apiKey) {
    throw new Error('GROQ_API_KEY not configured');
  }

  const systemPrompt = getSystemInstruction(normalizedMode);
  const userPrompt = buildPrompt(normalizedMode, context);

  try {
    console.log(`[Groq] Generating ${normalizedMode} documentation...`);
    console.log(`[Groq] Model: ${model}`);
    console.log(`[Groq] Input size: ${context.length} chars`);

    const response = await fetchWithRetry(
      `${GROQ_API_BASE}/chat/completions`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: model,
          messages: [
            {
              role: 'system',
              content: systemPrompt,
            },
            {
              role: 'user',
              content: userPrompt,
            },
          ],
          temperature: 0.3,
          max_tokens: 4096,
          top_p: 0.8,
        }),
        timeoutMs: 90000,
        attempts: 2,
        baseDelayMs: 1000,
        maxDelayMs: 10000,
      },
    );

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('[Groq] API error:', errorData);
      throw new Error(
        `Groq API failed: ${response.status} - ${
          errorData.error?.message || 'Unknown error'
        }`,
      );
    }

    const data = await response.json();

    if (!data.choices || data.choices.length === 0) {
      throw new Error('No content generated by Groq');
    }

    const messageContent = data.choices[0].message?.content;
    if (!messageContent) {
      throw new Error('Invalid response structure from Groq');
    }

    console.log(`[Groq] Generation complete: ${messageContent.length} chars`);
    return stripMarkdownFence(messageContent);
  } catch (error) {
    console.error('[Groq] Error:', error);
    throw new Error(`Failed to generate documentation with Groq: ${error.message}`);
  }
}

function getSystemInstruction(mode) {
  if (mode === 'architecture') {
    return `You are a Senior Software Architect with deep expertise in system design, distributed systems, and technical communication. Your job is to analyze a CONTEXT DUMP and transform it into comprehensive, professional architecture documentation.

Generate documentation following EXACTLY this 5-section structure in ENGLISH:

# [System/Component Name] - Architecture

## Overview
Summarize what the system/component is, its business purpose, primary users, and the problems it solves.

## Key Components
List the principal components/services with descriptions of their responsibilities.

## Data & Service Flow
Describe how data and requests move through the system at runtime with a numbered list or diagram.

## Technology Stack
List key technologies, frameworks, databases, infrastructure, and tooling.

## Migration Guide & Developer Workflow
Detail step-by-step developer workflow, setup steps, commands, and deployment process.

Output MUST be 100% in ENGLISH. Use Markdown formatting with headings, bullets, and code blocks.`;
  }

  if (mode === 'meeting') {
    return `You are an expert Technical Project Manager and Systems Analyst. Your job is to analyze MEETING TRANSCRIPTS and transform them into clear, actionable technical documentation in ENGLISH.

Generate meeting documentation following EXACTLY this 6-section structure in ENGLISH:

# Meeting Record: [Create a concise title]

## Executive Summary
Provide a 3-5 sentence summary of the meeting's primary objective, key outcomes, and overall sentiment.

## Key Decisions & Definitions
List explicit agreements made during the meeting.

## Technical Context Extracted
Identify technical details: technologies mentioned, architectural changes, data points discussed.

## Action Items & Next Steps
Extract clear tasks with owners and deadlines.

## Open Questions & Risks
List unresolved items or potential problems raised.

OUTPUT MUST be 100% in ENGLISH. Ignore filler words and focus on substantial content.`;
  }

  return `You are a Staff-level Data Engineer and expert Technical Communicator. Your job is to analyze a CONTEXT DUMP and transform it into clear, concise, high-quality technical documentation.

Generate documentation following EXACTLY this 5-section structure in ENGLISH:

# [Task Title with Identifier if present]

## Summary
Write 1-2 sentences summarizing the task and its purpose.

## Problem Solved
Explain the business or technical problem this task addressed.

## Solution Implemented
Describe the technical approach, architecture decisions, data flows, and tooling used.

## Code Highlights / Key Artifacts
Show the most critical code snippets with brief explanations. For SQL solutions, include full queries. For application code, show 2-3 focused snippets (5-15 lines).

## Challenges & Learnings
List key obstacles, mitigations, risks, or lessons learned as bullet points.

Output MUST be 100% in ENGLISH. Use Markdown formatting with code blocks.`;
}

function buildPrompt(mode, context) {
  return `Process the following CONTEXT DUMP and generate ${mode} documentation in ENGLISH following the structure defined in the system instruction:\n\n**CONTEXT:**\n${context}\n\nGenerate comprehensive documentation now.`;
}

function stripMarkdownFence(text) {
  if (!text) return text;
  const trimmed = text.trim();
  if (!trimmed.startsWith('```')) return text;
  const fenceMatch = trimmed.match(/^```[a-zA-Z0-9+-]*\n([\s\S]*?)\n```$/);
  if (!fenceMatch) return text;
  return fenceMatch[1].trim();
}