/**
 * @fileoverview Google Gemini API Integration for Technical Documentation Generation
 * @module services/geminiService
 * @description Uses REST API with native fetch (no SDK required)
 */

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta/models';

/**
 * @async
 * @function generateDocumentation
 * @description Generates technical documentation in English using Gemini API with 5-section structure
 * @param {Object} input - The input data (accepts any language input)
 * @param {string} input.context - Context of the task (required)
 * @param {string} input.code - Code implementation (optional)
 * @param {string} input.challenges - Challenges/difficulties faced (optional)
 * @returns {Promise<string>} Generated documentation in English Markdown format
 * @throws {Error} When API key is missing, API request fails, or response is invalid
 */
export async function generateDocumentation({ context, code, challenges }) {
  const model = process.env.GEMINI_MODEL || 'gemini-2.0-flash-exp';
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    throw new Error('GEMINI_API_KEY not configured in environment variables');
  }

  const prompt = buildPrompt(context, code, challenges);
  const systemInstruction = getSystemInstruction();

  try {
    const response = await fetch(
      `${GEMINI_API_BASE}/${model}:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              role: 'user',
              parts: [{ text: prompt }],
            },
          ],
          systemInstruction: {
            parts: [{ text: systemInstruction }],
          },
          generationConfig: {
            temperature: 0.3,
            maxOutputTokens: 4096,
            topP: 0.8,
            topK: 40,
          },
        }),
      }
    );

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('Gemini API error:', errorData);
      throw new Error(
        `Gemini API failed: ${response.status} - ${
          errorData.error?.message || 'Unknown error'
        }`
      );
    }

    const data = await response.json();

    if (!data.candidates || data.candidates.length === 0) {
      throw new Error('No content generated by Gemini');
    }

    const candidate = data.candidates[0];
    if (!candidate.content || !candidate.content.parts) {
      throw new Error('Invalid response structure from Gemini');
    }

    const generatedText = candidate.content.parts
      .map((part) => part.text)
      .join('');

    return generatedText;
  } catch (error) {
    console.error('Error calling Gemini API:', error);
    throw new Error(`Failed to generate documentation: ${error.message}`);
  }
}

/**
 * @function getSystemInstruction
 * @description Builds the system instruction for Gemini - sets the model's role as a Staff-level Data Engineer and Technical Communicator
 * @returns {string} System instruction text in English
 */
function getSystemInstruction() {
  return `You are a Staff-level Data Engineer and expert Technical Communicator. Your job is to analyze raw task notes and transform them into clear, concise, high-quality technical documentation.

Your mission is to process three user inputs ($TASK_CONTEXT, $CODE_IMPLEMENTATION, $CHALLENGES) provided in ANY language.

Follow this 3-step process:
1. [ANALYZE & TRANSLATE]: Deeply analyze the content of all three inputs. Identify the core problem, technical solution, architectural decisions, and lessons learned. Mentally translate all content and concepts to ENGLISH.
2. [SYNTHESIZE]: Synthesize the translated information into cohesive, logical technical documentation. DO NOT just list the inputs; instead, structure the information into a narrative that explains what, why, and how.
3. [FORMAT]: Format the output as a clean, well-structured Markdown document following the required structure.

Guidelines:
- Accept input in any language but always output in ENGLISH
- Use technical but accessible language
- Be specific and detailed
- Format text in Markdown with headers, lists, and code blocks
- Maintain a professional and informative tone
- Structure content logically and hierarchically`;
}

/**
 * @function buildPrompt
 * @description Builds the user prompt for documentation generation
 * @param {string} context - Task context
 * @param {string} code - Code implementation
 * @param {string} challenges - Challenges faced
 * @returns {string} Complete prompt in English with 5-section structure
 */
function buildPrompt(context, code, challenges) {
  let prompt = `Process the following inputs and generate technical documentation:

**$TASK_CONTEXT:**
${context}
`;

  if (code && code.trim()) {
    prompt += `\n**$CODE_IMPLEMENTATION:**
\`\`\`
${code}
\`\`\`
`;
  }

  if (challenges && challenges.trim()) {
    prompt += `\n**$CHALLENGES:**
${challenges}
`;
  }

  prompt += `\n
Generate documentation following EXACTLY this structure in ENGLISH:

# [Concise and Descriptive Task Title]

## Summary
Write 1-2 sentences in English summarizing the task and its purpose.

## Problem Solved
Describe the business or technical problem that this task solved, based on the $TASK_CONTEXT.

## Solution Implemented
Describe the technical approach and key implementation decisions. If the $TASK_CONTEXT mentions why one approach was chosen over another, include that.

## Code Highlights
Provide a brief explanation of the code snippet, highlighting its main function in the solution.
\`\`\`
# Insert the $CODE_IMPLEMENTATION here
# Try to infer the language (ex: python, sql, javascript) and use it in the code block
\`\`\`

## Challenges & Learnings
Based on the $CHALLENGES, list the main obstacles or insights as bullet points.

- First challenge or lesson learned.
- Second challenge or lesson learned.

**Important:**
- Output MUST be 100% in ENGLISH
- Use Markdown with ## for main sections
- Include bulleted lists (-) when appropriate
- Be detailed and specific in each section
- Infer and specify the code language in code blocks (e.g., \`\`\`python, \`\`\`sql, \`\`\`javascript)
- Maintain technical focus with clarity`;

  return prompt;
}
