/**
 * @fileoverview Google Gemini API Integration for Technical Documentation Generation
 * @module services/geminiService
 * @description Uses REST API with native fetch (no SDK required)
 */

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta/models';

/**
 * @async
 * @function generateDocumentation
 * @description Generates technical documentation in Portuguese using Gemini API
 * @param {Object} input - The input data
 * @param {string} input.context - Context of the task (required)
 * @param {string} input.code - Code implementation (optional)
 * @param {string} input.challenges - Challenges/difficulties faced (optional)
 * @returns {Promise<string>} Generated documentation in Markdown
 * @throws {Error} When API key is missing, API request fails, or response is invalid
 */
export async function generateDocumentation({ context, code, challenges }) {
  const model = process.env.GEMINI_MODEL || 'gemini-2.0-flash-exp';
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    throw new Error('GEMINI_API_KEY not configured in environment variables');
  }

  const prompt = buildPrompt(context, code, challenges);
  const systemInstruction = getSystemInstruction();

  try {
    const response = await fetch(
      `${GEMINI_API_BASE}/${model}:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              role: 'user',
              parts: [{ text: prompt }],
            },
          ],
          systemInstruction: {
            parts: [{ text: systemInstruction }],
          },
          generationConfig: {
            temperature: 0.3,
            maxOutputTokens: 4096,
            topP: 0.8,
            topK: 40,
          },
        }),
      }
    );

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('Gemini API error:', errorData);
      throw new Error(
        `Gemini API failed: ${response.status} - ${
          errorData.error?.message || 'Unknown error'
        }`
      );
    }

    const data = await response.json();

    if (!data.candidates || data.candidates.length === 0) {
      throw new Error('No content generated by Gemini');
    }

    const candidate = data.candidates[0];
    if (!candidate.content || !candidate.content.parts) {
      throw new Error('Invalid response structure from Gemini');
    }

    const generatedText = candidate.content.parts
      .map((part) => part.text)
      .join('');

    return generatedText;
  } catch (error) {
    console.error('Error calling Gemini API:', error);
    throw new Error(`Failed to generate documentation: ${error.message}`);
  }
}

/**
 * @function getSystemInstruction
 * @description Builds the system instruction for Gemini - sets the model's role as a senior technical writer for data engineering
 * @returns {string} System instruction text in Brazilian Portuguese
 */
function getSystemInstruction() {
  return `Você é um redator técnico sênior especializado em engenharia de dados e documentação técnica.

Sua função é criar documentação técnica profissional, clara e detalhada no formato de manual de instruções, sempre em Português do Brasil.

Diretrizes:
- Use linguagem técnica mas acessível
- Seja específico e detalhado
- Formate o texto em Markdown com cabeçalhos, listas e blocos de código
- Mantenha tom profissional e informativo
- Forneça exemplos práticos quando apropriado
- Estruture o conteúdo de forma lógica e hierárquica`;
}

/**
 * @function buildPrompt
 * @description Builds the user prompt for documentation generation
 * @param {string} context - Task context
 * @param {string} code - Code implementation
 * @param {string} challenges - Challenges faced
 * @returns {string} Complete prompt in Brazilian Portuguese
 */
function buildPrompt(context, code, challenges) {
  let prompt = `Crie uma documentação técnica completa e profissional sobre a seguinte tarefa de engenharia de dados:

**Contexto da Tarefa:**
${context}
`;

  if (code && code.trim()) {
    prompt += `\n**Implementação do Código:**
\`\`\`
${code}
\`\`\`
`;
  }

  if (challenges && challenges.trim()) {
    prompt += `\n**Desafios/Dificuldades Enfrentadas:**
${challenges}
`;
  }

  prompt += `\n
Gere a documentação seguindo EXATAMENTE esta estrutura:

# Documentação Técnica

## 1. Visão Geral da Tarefa
[Descreva o objetivo principal da tarefa e sua importância no contexto de engenharia de dados]

## 2. Contexto e Motivação
[Explique o contexto do problema, por que esta solução foi necessária e qual problema ela resolve]

## 3. Solução Implementada
[Descreva em detalhes a solução técnica implementada, incluindo tecnologias, arquitetura e abordagem]

## 4. Dificuldades Encontradas
[Liste e explique as principais dificuldades encontradas durante a implementação]

## 5. Armadilhas e Pontos de Atenção
[Identifique possíveis armadilhas, edge cases e pontos que merecem atenção especial]

## 6. Soluções Aplicadas
[Explique as soluções encontradas para cada dificuldade, incluindo alternativas consideradas]

## 7. Lições Aprendidas
[Resuma os principais aprendizados dessa experiência e insights obtidos]

## 8. Recomendações Futuras
[Forneça recomendações para trabalhos futuros, melhorias possíveis e próximos passos]

**Importante:**
- Use Markdown com ## para seções principais
- Inclua listas com marcadores (-) quando apropriado
- Seja detalhado e específico em cada seção
- Mantenha o foco técnico mas com clareza`;

  return prompt;
}
